version: "3"
services:
  daily-report:
    container_name: Daily-Report
    tty: true
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /daily-report
    volumes:
      - .:/daily-report
    ports:
      - 8080:8080
    # network_mode: host
    networks:
      my-net:
        ipv4_address: 172.26.1.2
    # command: ./start.sh
    depends_on:
      - database
  database:
    image: postgres
    restart: always
    env_file:
      - .env
    environment:
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"
    # volumes:
    #   - data:/var/lib/postgresql/data
    networks:
      my-net:
        ipv4_address: 172.26.1.3


networks:
 my-net:
  ipam:
   driver: default
   config:
    - subnet: 172.26.0.0/16

# volumes:
#   data: